[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'Installing dependencies...'",
  "npm install",
  "echo 'Generating Prisma client...'",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
